#!/usr/bin/env bash

## https://github.com/cli/cli is used to fetch the dependent jars fromm the repository Releases
## "ant getjars" will run
## gh release download 0.1 -p '*.jar' --dir lib --repo bartland-usi/sample-java
## Assets already fetched will not be refetched

ant getjars
ant -Dusiver=3 -Denv=3PT wsdl jar runUSITest

## after build, to just run
#ant -Dusiver=3 runUSITest
