#!/usr/bin/env bash

set -e
set -o pipefail

_() { if [[ $? -ne 0 ]]; then echo "ooopsie"; echo; fi }
trap _ ERR EXIT

## https://github.com/cli/cli is used to fetch the dependent jars fromm the repository Releases
## "ant getjars" will run
## gh release download 0.2 -p '*.jar' --dir lib --repo bartland-usi/sample-java
## Assets already fetched will not be refetched

echo "ant -Dusiver=5 -Dstsver=12 -Denv=3PT dumpvars getjars wsdl jar runUSITest"
ant -Dusiver=5 -Dstsver=12 -Denv=3PT dumpvars getjars wsdl jar runUSITest

## after build, to just run
#ant -Dusiver=4 runUSITest
